### ISSUE TITLE
Add support for self-signed SSL certificates

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors-bundle#108]
__What should we do?__

Introduce an ability to send requests with HTTP REST connector using custom certificates.

__Why should we do it?__

Some customers use HTTP REST connector in their isolated intranets. As such, (1) some of the services use self-signed / self-issued SSL certificates; (2) another use-case is mTLS AuthN.

**Comment by mbiciin** [comment]
More info here: #180

**Comment by mbiciin** [comment]
Updates: 
As discussed with Falko, we don't need to use the openapi library that he used in the code that he provided for help - >#180 . We need to provide the Apache HTTP Client created by HttpClients.createSystem() to the Google HTTP client. I did this in the class HttpTransportComponentSupplier.  This is the line where you provide the Apache HTTP Client to Google HTTP client: " private static final HttpTransport HTTP_TRANSPORT = new ApacheHttpTransport(HttpClients.createSystem());"

```
public class HttpTransportComponentSupplier {

  private HttpTransportComponentSupplier() {}
  static{
    // *
    System.setProperty("javax.net.ssl.keyStore", "/Users/mirabelabiicin/domain.pem");
    System.setProperty("javax.net.ssl.keyStorePassword", "test");
    System.setProperty("javax.net.ssl.keyStoreType", "PEM");
    // */
    System.setProperty("javax.net.debug", "ssl"); // TLS debug
    // System.setProperty("javax.net.debug", "ssl:handshake:verbose:keymanager:trustmanager"); //
    // very verbose debug
  }

  private static final HttpTransport HTTP_TRANSPORT = new ApacheHttpTransport(HttpClients.createSystem());
  private static final HttpRequestFactory REQUEST_FACTORY =
      HTTP_TRANSPORT.createRequestFactory(
          request ->
              request.setParser(new JsonObjectParser(GsonComponentSupplier.gsonFactoryInstance())));

  public static HttpRequestFactory httpRequestFactoryInstance() {
    return REQUEST_FACTORY;
  }
}
```
Falko said that he used keystore explorer and helped him while doing tests, but I saw that it's not supporting pem certificates.
He also said something about the openapi library: "Once the REST Connector can support client certificates, we will just generate element templates from the OpenAPI specification." I didn't ask more details about what he meant by that.

If you will need openapi, this is a tutorial about it: https://developer.mastercard.com/issm-merchant-enrollment/tutorial/generating-api-client/1/

How to generate certificates: https://www.baeldung.com/openssl-self-signed-cert
How to convert certificates: https://cheapsslsecurity.com/p/convert-a-certificate-to-pem-crt-to-pem-cer-to-pem-der-to-pem/
