### ISSUE TITLE
Download script for element-templates of all connectors in the latest version

### ISSUE THREAD

**Issue by rob2universe** [camunda/connectors-bundle#11]
__Is your feature request related to a problem? Please describe.__

As a Desktop Modeler user I want a convenient way to download the element-templates for all connectors in the latest version.
It is cumbersome to navigate to the currently 7 download locations and download the element-templates one by one, then place them into the model-elements folder

__Describe the solution you'd like__

the connector bundles repository could host scripts so all element templates can be added by running it.
(Ultimately the modeler should offer a built-in installation feature)

__Describe alternatives you've considered__

Created own script:
`wget -O - https://raw.githubusercontent.com/rob2universe/model-element-templates/main/download.sh | bash`

**Comment by tmetzke** [comment]
@rob2universe, would a download script that matches the runtime versions in the Docker image suffice for now? I believe users need to take it from there anyways, as we don't know where to place the templates and if they want to use them as-is or adjust them anyways.

**Comment by tmetzke** [comment]
This is superseded by #14. Closing this here for now. If we encounter that #14 doesn't suffice, we can reopen.
