### ISSUE TITLE
[Kafka] Configured connector does not deploy without `Additional 

### ISSUE THREAD

**Issue by nikku** [camunda/connectors-bundle#120]
__Describe the Bug__

If no additional properties (cf. screenshot below) are provided the process fails to deploy:

![image](https://user-images.githubusercontent.com/58601/208145951-be9b7f18-0ac5-406e-acbc-5640a5638fc0.png)

__Steps to Reproduce__

1. Model Kafka Connector
2. Omit `Additional Properties`
3. Deployment rejected

__Expected Behavior__

Does deploy, and only configures `Additional Properties` if needed.

__Environment__

- OS: Any
- Library version: Any
- Camunda version: latest

**Comment by nikku** [comment]
Root cause: We must configure [input and output mappings as `optional`](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/#optional-bindings) in the element template. They will otherwise be serialized as empty bindings (if not provided), and the engine will refuse to deploy them.

Cf. [this comment](https://camunda.slack.com/archives/C02JLRNQQ05/p1671208567257829?thread_ts=1671203872.848729&cid=C02JLRNQQ05)

**Comment by igpetrov** [comment]
This is applicable for other templates as well
