### ISSUE TITLE
UIPath error: 'queueItemParameters must not be null'

### ISSUE THREAD

**Issue by mbiciin** [camunda/connectors-bundle#127]
__Describe the Bug__

This error is return over and over again by uipath and it is not suggestive at all. After a lot of tests I found out that it happens when the headers or the body are not sent correctly or when they are not sent at all. The most frequent issue is that the body is not sent. This was mostly caused by the field SpecificContent which for some reason, needs a refresh sometimes, even if there is no referenced field in it as we have in the body. Maybe there is a problem if the value is in json format. 

![Screen Shot 2022-12-19 at 1 29 43 PM (2)](https://user-images.githubusercontent.com/114916619/208417846-c04f6106-34cc-465e-bc86-abd7990e93d4.png)

**Comment by nikku** [comment]
> This error is return over and over again by uipath and it is not suggestive at all. 

The error indicates that `queueItemParameters` must not be `null`. So how are `queueItemParameters` constructed and passed to the REST connector. Does there exist any meaningful debug information in operate?

**Comment by mbiciin** [comment]
@nikku there is not much thing in the operate. There is some escaping when the body is not sent. Can you see this process https://bru-3.operate.ultrawombat.com/e1508d68-7d89-47b9-91a6-49e8d845ab02/processes/4503599627682911 ?

**Comment by nikku** [comment]
@mbiciin I cannot see that process.

Please update the issue with concrete steps to reproduce and I can look into it in 2023.

**Comment by igpetrov** [comment]
Feels like related to https://github.com/camunda/zeebe/issues/9859

@mbiciin @nikku

**Comment by igpetrov** [comment]
@mbiciin this happens when you write JSON in a plain text field. Try to enforce FEEL expression and pass the JSON as FEEL model. That should remove escaping.

**Comment by mbiciin** [comment]
I closed this issue, because as confirmed with @nikku, we need to enforce the FEEL expression for the prefilled values.
