### ISSUE TITLE
Simplify authentication types

### ISSUE THREAD

**Issue by nikku** [camunda/connectors-bundle#137]
__Is your feature request related to a problem? Please describe.__

Right now our authentication types present the following options:

* `No Auth`
* `Basic Auth`
* `Bearer Token Auth`
* `OAuth 2.0`

I think we can better align these options, also taken into account the existing way we embed the options:

![image](https://user-images.githubusercontent.com/58601/208635861-ec79c993-e801-47a0-8581-83ba1f24e471.png)

__Describe the solution you'd like__

* Simplify options to
  * `None`
  * `Basic`
  * `Bearer Token`
  * `OAuth 2.0`
* Drop hint (does not provide additional information)

__Describe alternatives you've considered__

None.

__Additional context__

None.

**Comment by igpetrov** [comment]
Hi @mbiciin,

Can we close this ticket? Or is it anything pending?

**Comment by mbiciin** [comment]
Hi, 
Yes, I can close it.  It was merged.
