### ISSUE TITLE
Point to documentation on how to write a response mapping

### ISSUE THREAD

**Issue by christian-konrad** [camunda/connectors-bundle#158]
__What should we do?__

Add a link to the documentation (if no doc existing, write it) of how to create a response mapping.

![Bildschirmfoto 2022-12-24 um 10 41 49](https://user-images.githubusercontent.com/56470362/209430269-e2ea9807-a3d0-48a5-8b7f-c652f40205f0.png)

__Why should we do it?__

The response mapping in Connector templates/tasks is not self-explaining. A new user might drop off here, since it's completely different to how it works in other tasks, and there is no in-app guide, or link to any documentation. 

Related to https://github.com/camunda/connectors-bundle/issues/154; this one should be done first in case the inline help/tooltips are not yet available.

**Comment by MaxTru** [comment]
@bastiankoerber following up from the weekly: should we implent this short-term (it is low cost and could potentially add a lot of value)

**Comment by bastiankoerber** [comment]
sounds like an easy win. lets do it

**Comment by igpetrov** [comment]
So far:
- Created docs: https://github.com/camunda/camunda-platform-docs/pull/1636
- Created bundle draft PR - will be merged once docs updated: https://github.com/camunda/connectors-bundle/pull/227

Pending:
- Web Modeler PR. Will be created given above-mentioned PRs are merged

**Comment by igpetrov** [comment]
Doc is merged. Bundle is merged. Created a PR in web-modeler:

- https://github.com/camunda/web-modeler/pull/3624

**Comment by igpetrov** [comment]
Blocked by https://github.com/camunda/web-modeler/pull/3624#issuecomment-1405090864

**Comment by igpetrov** [comment]
Done
