### ISSUE TITLE
"["+"]" in connector JSON files prevent importing in Webmodeler (selfmanaged)

### ISSUE THREAD

**Issue by asys3** [camunda/connectors-bundle#18]
__Describe the Bug__

The includes element template files in the release bundle can't be imported in a selfmanaged webmodeler instance. 
For example: Error message: "The following 1 file is invalid and can't be uploaded: "slack-connector.json""
(If the leading "[" and ending "]" in the files are removed, everything works fine.)

__Steps to Reproduce__

1. Extract JSON files from connector-bundles-templates archive.
2. In Webmodeler Modeler Select -> New project -> New - Upload Files
3. Select one or more containing JSON files.
4. Select "Open"

__Expected Behavior__

Message like:
"aws-lambda-connector.json" is being uploaded.

__Environment__

- OS: [Windows 10]
- Library version: [0.1.2]
- Camunda version: [8.1.0 (self-managed)]

**Comment by nikku** [comment]
We'll move to flat template structure to allow easy incorporation into the web modeler.
