### ISSUE TITLE
Be able to plug-in secrets provider

### ISSUE THREAD

**Issue by nikku** [camunda/connectors-bundle#2]
__What shall we do__

Add an example that shows how to plug-in your own secrets provider.

__Why shall we do it?__

Having pluggable secret providers is a core proposition of connectors.

**Comment by tmetzke** [comment]
I also addressed this a bit in https://github.com/camunda/camunda-platform-docs/pull/1376/files#diff-2ae06ca82e6b8cb1e39bd3696027f566747ffc3007d4030aa50bc87f7d770a09R70-R91

**Comment by berndruecker** [comment]
Was fixed as part of https://github.com/camunda/team-connectors/issues/212
