### ISSUE TITLE
Create new version of custom template for uipath

### ISSUE THREAD

**Issue by mbiciin** [camunda/connectors-bundle#210]
__What should we do?__

We need to support two type of request in the custom template "Add queue item" and "Get item status". We will ad a dropdown list with thse 2 values. The input values from the custom template will have a display condition depending on the type of request selected from the dropdown list. Prefilled values will be used just for hidden fields. We will add notes/docs links as guideline for the user. 

__Why should we do it?__

https://github.com/camunda/product-hub/issues/190

**Comment by mbiciin** [comment]
@bastiankoerber, we forgot, for the request "Get item status", we need an item id for filtering the results. We should ask the user to add it manually? In the prototype diagram, we extracted the item id from the response of request "add queue item". We added some expressions there: https://modeler.cloud.dev.ultrawombat.com/diagrams/1798be99-cf98-4b1e-88b3-cb5cde3b6a5d--prototype-bpmn-uipath-bpmn?v=660,377,1 


![Image](https://user-images.githubusercontent.com/114916619/212298831-9724e9c6-dec8-40df-ae54-90b5ff13356e.png)

![Image](https://user-images.githubusercontent.com/114916619/212298903-c6c9836b-9aac-4faf-85a2-3129d390493a.png)

**Comment by mbiciin** [comment]
The user can build a similar diagram, but using the same template. Is this what we need?

**Comment by bastiankoerber** [comment]
btw: is it possible to have the itemid as an outputfield. Something like: ItemID and i enter the variablename ?

If this is not possible, i would prefill the result expression (like you did).

In the "get item status" i would add two input fields: Status (as dropdown) and item id (as input). The output can be prefilled if there is no possibility to have an "output field"

**Comment by mbiciin** [comment]
I think you can see this diagram from int: https://modeler.cloud.ultrawombat.com/diagrams/d71bcde7-2c2b-4a37-8b3d-eebdb690bf3e--prototype-uipath-diagram?v=660,377,1

**Comment by bastiankoerber** [comment]
> I think you can see this diagram from int: https://modeler.cloud.ultrawombat.com/diagrams/d71bcde7-2c2b-4a37-8b3d-eebdb690bf3e--prototype-uipath-diagram?v=660,377,1

just to make sure, that we are on the same page. The link shows our "old" templates right and not the production ready templates ([Release UI Path Connector#296](https://github.com/camunda/team-connectors/issues/296))

**Comment by mbiciin** [comment]
This url points to the prototype diagram. I linked it here to show how we implemented the expressions for "itemId" and "itemStatus".

As disscussed, we should improve the template as following:
- we will have two more input fields: "Item id" for operation "Add queue item" and "Item status" for operation 
 "Get item status"
- For input field "Item id" we should have the following behavior: we need a variable that should be displayed as an input field and let the user fill a name for the variable and we should bind this name with the value returned by a resultExpression (have prefilled value {itemId: response.body.id}). 
- we will keep the default "result variable" too ( with name introduced by the user e.g "test1")
-  in operate, we should see 2 result variables, "test1" with value of the entire response and "test2" with value returned by expression {itemId: response.body.id}. 
- similar behavior for "Item status", but with the following resultExpression: {itemStatus: response.body.value[1].Status}

We don't know if this requirement can be implemented. I tried different solutions and I didn't find an answer yet. I set a meeting with a collegue from web-modeler team today.

**Comment by mbiciin** [comment]
Issues that I had while creating the new version of the template and that slowed me down:
- I was not able to test on dev because we had an old bug in the backend code for the rest connector (field "audience" is still mandatory). We don't know why we still have this bug on dev, because it was fixed and delivered to prod. On int we don't have it anymore. Probably we have deployment issues.
- I was not able to test on dev and int because of the bug in the web-modeler concerning the ordering of the fields in the xml.
- I used the Desktop Modeler Nightly (because here we have the fix for the ordering bug) which is not stable, at least for MacOs. It doesn't get the changes in the template all the time so you don't know if what you changed in the template it is reflected in the diagram or not (especially if you make changes that are not visible) and it freezes sometimes at deployment.  I tried the reload button, force quiting the app. You need to try it few times in order to make the template changes be applied.
- Operate doesn't start correctly locally. You have to delete the platform containes, the volumes, do 3-4 restart ot make it work. 

@nikku, did you have the issue that I described above with the Desktop Modeler Nightly?

**Comment by nikku** [comment]
> You have to delete the platform containes, the volumes, do 3-4 restart ot make it work.

@mbiciin You need to reload the desktop modeler `CMD+R` for new templates to be loaded.

**Comment by mbiciin** [comment]
@nikku, seems that is not always working. If I add a new input field, for example, it will be updated indeed. But if I update the  prefilled values in the template, they are not updated after reload in the diagram.

**Comment by nikku** [comment]
> @nikku, seems that is not always working. If I add a new input field, for example, it will be updated indeed. But if I update the prefilled values in the template, they are not updated after reload in the diagram.

What you are experiencing with "not updating" is best described with what happens when you monkey patch element templates; do not apply changes through explicit upgrading. 

Templates won't magically update your default inputs, unless you explicitly update to a new version. 

#### Test it yourself

* Update a template that is selected on a task
* You don't see new defaults applied
* Create a new task, apply the updated template to it
* See the new defaults applied

**Comment by mbiciin** [comment]
@nikku, it looks like a bug to me or it is a known issue and creating again the diagram it is the workaround. I don't see why it updates the rest of the properties, except the prefilled values. I tested by recreating the diagram and it was really time consuming to type type the values that I needed every time. I suppose that if you don't change too ofen the template, as I needed to do, then it's not a problem.

**Comment by bastiankoerber** [comment]
> @nikku, it looks like a bug to me or it is a known issue and creating again the diagram it is the workaround. I don't see why it updates the rest of the properties, except the prefilled values. I tested by recreating the diagram and it was really time consuming to type type the values that I needed every time. I suppose that if you don't change too ofen the template, as I needed to do, then it's not a problem.

@mbiciin  can you create a short video with your issue? i just want to make sure, that we all have the same understanding

**Comment by mbiciin** [comment]
@bastiankoerber, I will create a video. 
Concerning the issue that I had with the "itemId" with value null in the "Filters" expression,apparently you need to add a conversion to string. I used the same expression that we had in the prototype template where it worked ("={\"$Filter\":\"Id eq \"+itemId}"). I don't see why here it needs a conversion for the variable "itemId". The new expression is: "={\"$Filter\":\"Id eq \"+string(itemId)}". 

About the two new input fields "Item Id" and "Item status", there is a way to let the use type the name and bind the name with the value of the itemId that we extract from the resultExpression as following:
```
 {
        "label": "Item ID",
        "description": "Add your Item Queue ID ",
        "group": "output",
        "type": "String",
        "binding": {
          "type": "zeebe:output",
          "source": "=items.itemId"
        },
        "condition": {
          "property": "operationType",
          "oneOf": [
            "addQueueItem"
          ]
        }
      }
```
You need to use zeebe:output which requirea a source. The source will be the "itemId". If you want to let the user introduce the name, you don't add a name in the binding section.
 But there is a problem. You cannot use this variable anymore in the filter, because you don't know what name was introduced by the user. We reference the itemId in the filter by name. I tryed to create a sort of a copy of the itemId but it didn't work: 
```
{
      "label": "Result Expression",
      "id": "resultExpressionAdd",
      "description": "Expression to map the response into process variables",
      "group": "output",
      "type": "String",
      "feel": "required",
       "value": "{items:{itemId: response.body.Id, itemIdCopy:response.body.Id}}"
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "resultExpression"
      },
      "condition": {
        "property": "operationType",
        "oneOf": [
          "addQueueItem"
        ]
      }
    },
 {
        "label": "Item ID",
        "description": "Add your Item Queue ID ",
        "group": "output",
        "type": "String",
        "binding": {
          "type": "zeebe:output",
          "source": "=items.itemId"
        },
        "condition": {
          "property": "operationType",
          "oneOf": [
            "addQueueItem"
          ]
        }
      },
    {
      "label": "Item ID Copy",
      "description": "Add your Item Queue ID ",
      "group": "output",
      "type": "Hidden",
      "binding": {
        "type": "zeebe:taskHeader",
        "key": "abc",
        "name": "abc",
        "source": "=items.itemIdCopy"
      },
      "condition": {
        "property": "operationType",
        "oneOf": [
          "addQueueItem"
        ]
      }
    },
{
      "label": "Filters",
      "description": "Map of query parameters to add to the request URL",
      "group": "input",
      "type": "Hidden",
      "value": "={\"$Filter\":\"Id eq \"+string(abc)}",
      "binding": {
        "type": "zeebe:input",
        "name": "queryParameters"
      },
      "condition": {
        "property": "operationType",
        "oneOf": [
          "getItemStatus"
        ]
      }
    },
```

I did a commit with the last changes. I kept the resultExpressions visible for now and deleted the new input fields.

**Comment by mbiciin** [comment]
I discussed about it with the colleague from 'ask-desktop-modeler-and-bpmn-io-team' and he said that it is not possible to change let he user change the name of the "itemId" and still use this variable in the filter.

**Comment by nikku** [comment]
@mbiciin There exists a `get_value(context, name)` function. Maybe that helps you to implement dynamic addressing / filtering?

**Comment by mbiciin** [comment]
Almost finished. I just have to add the link to the documentation.

**Comment by nikku** [comment]
I've synchronized with @mbiciin on this cf. https://github.com/camunda/connectors-bundle/pull/212#issuecomment-1398246303 and am happy to dive into the details of https://github.com/camunda/connectors-bundle/issues/210#issuecomment-1387421948, too.

What it looks like to me is that we use `itemID` in two different ways:

* :one: produced as an output of "add queue item"
* :two: required as an input of "get queue item"

In the :two: case it (obviously) must be passed into the connector, while in the :one: case it may produced.

Both things are possible, using existing facilities, I think.

**Comment by mbiciin** [comment]
@igor, here is what is left to do for uipath:
- task #231 
- review documentation: https://github.com/camunda/camunda-platform-docs/pull/1638
- update documentation after completing task #231 
- add custom template in web-modeler

Thank you! :)

**Comment by igpetrov** [comment]
So far:
- Desktop version works just fine
- SaaS version has following bugs:
- - OAuth fields are initially not populated
- - Operation fields are nitially not populated
- - Diagram requires `Item ID name` field to be populated

**Comment by igpetrov** [comment]
UIPath is now in web-modeler. It is hidden behind the feature flag.
