### ISSUE TITLE
UIPath: add new process variables in custom template

### ISSUE THREAD

**Issue by mbiciin** [camunda/connectors-bundle#231]
__What should we do?__

We will have two more input fields: "Item id" for operation "Add queue item" and "Item status" for operation
"Get item status".
For input field "Item id" we should have the following behavior: we need a variable that should be displayed as an input field and let the user fill a name for the variable and we should bind this name with the value returned by a resultExpression (have prefilled value {itemId: response.body.id}). 
There is a way to let the user type the name and bind the name with the value of the itemId that we extract from the resultExpression:
```
 {
        "label": "Item ID",
        "description": "Add your Item Queue ID ",
        "group": "output",
        "type": "String",
        "binding": {
          "type": "zeebe:output",
          "source": "=itemId"
        },
        "condition": {
          "property": "operationType",
          "oneOf": [
            "addQueueItem"
          ]
        }
      }
```
You need to use zeebe:output which requirea a source. The source will be the "itemId". If you want to let the user introduce the name, you don't add a name in the binding section.
But there is a problem. You cannot use this variable anymore in the filter, because you don't know what name was introduced by the user. We reference the itemId in the filter by name. Suggestion from Nico that may solve this issue: "There exists a get_value(context, name) function. Maybe that helps you to implement dynamic addressing / filtering?"

Similar for itemStatus, but using expression "={itemStatus: response.body.value[1].Status}" from "Result Expression Get". 

__Why should we do it?__

To make the custom template more user friendly. 

Related issues: #210

**Comment by igpetrov** [comment]
That is done.

<img width="393" alt="Screenshot 2023-02-06 at 13 42 46" src="https://user-images.githubusercontent.com/108870003/216962806-0dd10b18-15f6-46e5-8d16-cc7254b7e704.png">
