### ISSUE TITLE
Double check `bash` variant of bundle

### ISSUE THREAD

**Issue by berndruecker** [camunda/connectors-bundle#32]
__What should we do?__

- Decide if we still need it
- Pro:
  -  Template/Example to do a non-java bundle of connectors
- Con:
  - Maintenance effort and the risk of problems going unnoticed
- Alternative:
  - Move the bash bundle to some example repository, to manage expactations.

**Comment by tmetzke** [comment]
Superseded by https://github.com/camunda/team-connectors/issues/258
