### ISSUE TITLE
Validate workflows for monorepo

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors-bundle#37]
__What should we do?__

- Make sure workflows are correct and work as expected
- Do an alpha release
- Update team documentation

**Comment by tmetzke** [comment]
Regarding documentation, we also need to fix this repository regarding links to the Connector Runtime. It currently points to the now-removed `runtime` module. Can you tackle that? 🙂

**Comment by tmetzke** [comment]
By the way, can we also adjust https://github.com/camunda/connector-runtime-docker/blob/main/.github/workflows/RELEASE.yaml in the same way, maybe? Just to be consistent.
