### ISSUE TITLE
Investigate: Connectors Bundle fail to launch in private cloud Kubernetes, but works in AWS EKS

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors-bundle#442]
Copy and reference for the support request https://jira.camunda.com/browse/SUPPORT-16379

A customer is facing issues to run the connectors bundle in a private k8s cloud which works in AWS EKS for them:

```
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/connectors/certificates/elasticsearch.jks -Djavax.net.ssl.trustStorePassword=changeit
[0.013s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources. 
```

The issue was raised on slack via our #ask-connectors slack channel by https://camunda.slack.com/archives/C02JLRNQQ05/p1680621488734579

This task is for reference and to provide information for everyone who has no access to our support JIRA.

**Comment by igpetrov** [comment]
Checked that the current image is working on `jammy`. Next steps: build `focal` or `alpine` and get back to customers to suggest them to try a new image.

**Comment by igpetrov** [comment]
Cut a `connectors-bundle:0.18.0-focal` https://hub.docker.com/layers/camunda/connectors-bundle/0.18.0-focal/images/sha256-a[%E2%80%A6]f1c65d03d5d1a63d154a718f5d8878aaf2e8fb0d0d98b?context=explore.

Waiting for feedback.
