### ISSUE TITLE
Invalid error is thrown on session timeout

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/connectors-bundle#45]
__Describe the Bug__

When we create a Kafka connector and try to view the instance of the same in Operate we could see an error is thrown when the connection to the connector has timed out. But the error thrown is not valid to the timeout issue.

__Steps to Reproduce__

1. Create a BPMN diagram with Kafka connector
2. Fill in all the necessary fields and add a topic (that does not exist to introduce delay ) and deploy the diagram
3. Start and instance and view the instance in Operate
4. We could see that instance is waiting for a longer time in the connector and then throws the following error in Operate

<img width="776" alt="e11958ac8d40fd9bd131a8afc2d04f63" src="https://user-images.githubusercontent.com/85225325/203319184-e81f0dbc-b0fa-4384-8d8b-66596bdde6bb.png">

Configuration  in the connector

https://user-images.githubusercontent.com/85225325/203319430-5612ba60-abb9-4b78-b011-71956f375bf2.mp4

__Expected Behavior__

Correct error message should be thrown while there is connection time out in the connector

__Environment__

- OS: [Windows 10]
- Camunda Cloud Environment: [staging]

**Comment by igpetrov** [comment]
Thanks for the follow up, @tmetzke 

Just tested with the latest snapshot: https://bru-2.operate.ultrawombat.com/ec45c891-baea-4978-8d8f-ecb4c58c88f7/processes/2251799813685351.

Confirmed working. Closing.

<img width="398" alt="Screenshot 2022-12-09 at 15 51 18" src="https://user-images.githubusercontent.com/108870003/206717457-a0ef218a-0e68-4257-936b-d8e099e7e3f0.png">

<img width="1312" alt="Screenshot 2022-12-09 at 15 50 57" src="https://user-images.githubusercontent.com/108870003/206717446-85fb659a-e937-42cb-a783-273e948cad3e.png">
