### ISSUE TITLE
Process instance variable named `body` causes unexpected error

### ISSUE THREAD

**Issue by upgradingdave** [camunda/connectors-bundle#47]
__Describe the Bug__

If a process instance variable named `body` exists before a REST Connector GET Task, the Rest Connector Task will fail with the following error message: 

```
Failed to invoke connector, received the following error: Apache HTTP client does not support GET requests with content.
```

__Steps to Reproduce__

1. Create a simple process with a single REST Connector Task that does a simple GET request. For example: 

![Screen Shot 2022-09-21 at 4 41 58 PM](https://user-images.githubusercontent.com/939229/191606468-256307b9-c7d2-4560-9887-e982d6ed872f.png)

2. Run the process, and verify it works as expected

![Screen Shot 2022-09-21 at 4 44 00 PM](https://user-images.githubusercontent.com/939229/191606710-7eb11f20-913e-40fe-9beb-163735494e7a.png)

3. Edit the Start Node on the Model to create an instance variable named `body`. For example: 

![Screen Shot 2022-09-21 at 4 45 25 PM](https://user-images.githubusercontent.com/939229/191606975-669beb7e-e534-4e81-8192-dfbc2b881c79.png)

4. Rerun the process. The Task will fail, with the following message: 

```
Failed to invoke connector, received the following error: Apache HTTP client does not support GET requests with content.
```
![Screen Shot 2022-09-21 at 4 47 44 PM](https://user-images.githubusercontent.com/939229/191607301-664ff165-004b-41ec-94c2-8cd4cf7929a0.png)

__Expected Behavior__

A GET REST Connector Task should succeed even if there is an instance variable named "body". 

I'm guessing that the REST connector is using a variable named `body` internally? Maybe the internally used variable names can be name spaced? Maybe something like `rest_connector_body`, etc? Or maybe even better, the variable names can be uniquely generated using a guid? `body_<guid>`?

__Environment__

- Camunda Cloud Environment: SaaS v8.0.6

**Comment by nikku** [comment]
@tmetzke This is not about REST but strikes us everywhere, across all input bindings.

Fix needs to happen via https://github.com/camunda/zeebe/issues/11163 and rolled out across our element templates (enable no-magic input mapping).

**Comment by tmetzke** [comment]
Thanks, @nikku, makes sense. It initially came from the REST Connector, that's why I added that label when transferring the issue. The original description also still is very much REST-related.

I can see the broader scope this got over time. Maybe we can adjust the description as well to reflect that. It also makes sense to use a more general scope label then.

**Comment by nikku** [comment]
Created internal tracking issue for overall endeavour. Not ready to be picked up; just a tracking issue at this stage: https://github.com/camunda/team-connectors/issues/267.

**Comment by tmetzke** [comment]
Thank you, @nikku 👍
