### ISSUE TITLE
Allow adding custom http headers to GraphQL connector

### ISSUE THREAD

**Issue by bulivlad** [camunda/connectors-bundle#477]
__Is your feature request related to a problem? Please describe.__

As part of Camunda <-> GraphQL server integration we need to pass custom headers as part of the HTTP request.

__Describe the solution you'd like__

Allow custom http headers to be defined in the modeler as part of GraphQL connector attributes. As the GraphQL Request object extends the CommonRequest class, the headers fields are already in the code, just needed to be exposed in the modeler

__Describe alternatives you've considered__

As an alternative we can extend the GraphQL connector function and supply a custom request factory containing a request interceptor which will add the custom headers on the fly.

__Additional context__

Raised a PR here https://github.com/camunda/connectors-bundle/pull/476 to cover this functionality

**Comment by bastiankoerber** [comment]
@igpetrov or @markfarkas-camunda if we accepted the PR, can we close this ticket?
