### ISSUE TITLE
Allow the run-time to be re-used by custom connectors

### ISSUE THREAD

**Issue by nikku** [camunda/connectors-bundle#50]
__Define the problem__

As a user I'd like to define an element template with domain specific input and output bindings, re-using this connector run-time. This saves me a bunch of time as I only need to design an element template and not care about deploying another connector run-time.

In order for this to work the run-time needs to be able to handle more dynamic headers to assemble the HTTP connector input and extract the output (cf. [ref](
https://camunda.slack.com/archives/C02JLRNQQ05/p1657268963797159?thread_ts=1656674302.214659&cid=C02JLRNQQ05)).

**Example:** Querying the value of a currency

* Hard coded (template defined): Base URL `https://my-currency-checker/value`
* User-defined: is the currency type `currency` which shall be used as a query parameter
* User-defined: is the variable to store the currency value in `currencyValue`.
* The HTTP connector uses the currency type to craft the query parameters dynamically (`GET https://my-currency-checker/value?currency=BTC`)
* The HTTP connector uses the output variable to serialize the response dynamically `{ currencyValue: response.data.value }`

__Describe the solution__

* Supports dynamic creation of headers/query parameters to craft the HTTP request
* Support dynamic extraction of data from the response

__Alternatives you considered__

Require separate connector run-times for "custom HTTP connectors".

-----

Brought up in a couple of places, including [this discussion](https://camunda.slack.com/archives/C02JLRNQQ05/p1656674302214659).

**Comment by MaxTru** [comment]
Once we have https://github.com/camunda/web-modeler/issues/3251 fixed, one should be able to define fields in the element template that depend on each other, thereby creating dynamic inputs / outputs. So IMO we can fix this on element template level with https://github.com/camunda/web-modeler/issues/3251.

Is there more you expect here @nikku

**Comment by nikku** [comment]
This is in essence what we nowadays call "protocol connectors". Great to see us being able to close this 🎉
