### ISSUE TITLE
Store inbound connector errors

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors-bundle#514]
### What do we need to do?

Connector runtime needs to store errors that happen in the following cases:
- During inbound connector activation (i.e. in a synchronous call to `activate()` method)
- During `InboundConnectorExecutable` lifecycle (i.e. when connector declares an error by calling the `cancel()` method of the `InboundConnectorContext`.

We also need to return this information from our status endpoint (GET `/inboung`) alongside running connectors.

### Why do we need to do it?

To provide the user with debug information about errors that happened during inbound connector execution.

### Additional info

This issue was transferred from [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe/issues/401) repo.

**Comment by sbuettner** [comment]
Its already available and based on the [health indicator](https://github.com/camunda/connector-sdk/issues/462) implementation. I could imagine to have a proper schema for errors to properly present it in the modeler. Should we decide on an API schema for returning errors like https://jsonapi.org/format/#error-objects but maybe streamlined and simpler like:
```
...
error: {
  code: "AN_ERROR_CODE_THAT_CAN_BE_MAPPED"
  message: "A human readable error message".
}
...
```
?
