### ISSUE TITLE
Add templating support for URL

### ISSUE THREAD

**Issue by menski** [camunda/connectors-bundle#52]
Right now the connector doesn't support templating for fields like the URL. See related discussion https://github.com/camunda-community-hub/zeebe-http-worker/issues/210

**Comment by MaxTru** [comment]
Once we have https://github.com/camunda/web-modeler/issues/3251 implemented (and it is already in progress), we can dynamically create inputs by combining inputs from multiple fields. Hence we could construct a dynmiac URL for example. 

I assume that is a sufficient first iteration. Please feel free to re-open if we need more or if I miss something here.
