### ISSUE TITLE
Improved view of available OOTB Connectors

### ISSUE THREAD

**Issue by tmetzke** [camunda/connectors-bundle#534]
__Is your feature request related to a problem? Please describe.__

Looking at the [list of available out of the box Connectors](https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/available-connectors-overview/#outbound-connectors), it's becoming tougher to keep a comprehensive overview with a growing plain list.

__Describe the solution you'd like__

A more compelling and comprehensive view of the available Connectors. This could include any of the following:

* Card or tile view including an icon, short description, and maybe category (e.g. RPA, Production Tools, Protocol).
* Paged view with a search field to quickly find a Connector linked to a specific technology.
* Category filter to search for Connectors relevant to a certain area.

__Describe alternatives you've considered__

* Keep the current plain text list of Connectors.
* Wait for the Connectors Marketplace initiative to handle this.

__Additional context__

* The [Zapier apps view](https://zapier.com/apps) is quite nice to consume. It doesn't have to be as sophisticated in our reference documentation but can serve as an inspiration maybe.
* Microsoft's [Power Platform Connector reference](https://learn.microsoft.com/en-us/connectors/connector-reference/) is not very easy on the eye if you ask me, lots of clutter and not easy to navigate. I would leave that here as an example of disimproving such a list.
* We use cards already in our documentation, e.g. in the [APIs & tools part](https://docs.camunda.io/docs/next/apis-tools/working-with-apis-tools/).

**Comment by sbuettner** [comment]
As discussed with @bastiankoerber, this will be covered by the marketplace initiative.
