### ISSUE TITLE
Merge connector-runtime-docker repo into the bundle project

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors-bundle#538]
We currently provide example docker images and build instructions in a separate repository: https://github.com/camunda/connector-runtime-docker/tree/main

We should strive to have less moving pieces that can get out of date and should therefore merge it into the connectors-bundle project.

**Comment by chillleader** [comment]
Contents of the runtime-docker repo have been moved to the connectors-bundle as part of #804. The [old repo](https://github.com/camunda/connector-runtime-docker) is now archived.
