### ISSUE TITLE
Support "Create Channel" operation

### ISSUE THREAD

**Issue by MaxTru** [camunda/connectors-bundle#55]
__Is your feature request related to a problem? Please describe.__

* Currently the Slack conenctor only allows you to send messages to channels or individuals
* Typical use-cases however also involve creation of channel. Consider:
  * Incident is reported. Then Camunda to:
    1. Create an incident channel with a custom incident number related name
    2. Send a message to that channel
    3. (Next step, not for this issue) invite people to this channel

__Describe the solution you'd like__

* Make the existing Slack connector dynamic
* Support "Create channel" operation

### Breakdown of implementation tasks

- [x] Adjust element template with a `condition` (consider existing `method`) input
  - [x] Consider input: channel name (FEEL or static)
  - [x] Consider result: _probably return created channel name, ID, and status?_
- [x] Adjust backend implementation (connector function)
  - [x] Business logic
  - [x] Automated tests (API mock)
- [x] Adjust [documentation](https://github.com/camunda/camunda-platform-docs/pulls?q=is%3Apr+is%3Aclosed+label%3Aepic%3Aoptimize-versions+)
- [x] Consider migration case
  - [x] Ensure it works by trying out: e.g., have existing process with old template applied, and then change template under the hood => see what happens
    - [x] Learning excercise: learn about the `version` attribute in element templates which can be an alternative to an implicit migration
- [x] Change element template in Web Modeler
- [x] Deploy the new Connector run-time

__Describe alternatives you've considered__

* Create a seperate connector

__Additional context__

Part of camunda/team-connectors#192

**Comment by igpetrov** [comment]
Connector's in prod
