### ISSUE TITLE
Support "Invite User to Channel" operation

### ISSUE THREAD

**Issue by MaxTru** [camunda/connectors-bundle#56]
__Is your feature request related to a problem? Please describe.__

* Currently the Slack conenctor only allows you to send messages to channels or individuals, or to create channels
* Typical use-cases however also involve invitations of users to channels. Consider:
  * Incident is reported. Then Camunda to:
    1. Create an incident channel with a custom incident number related name
    2. Send a message to that channel
    3. **Invite people to this channel**

__Describe the solution you'd like__

* Support "Invite people to channel" operation in the existing Slack Connector 

### Breakdown of implementation tasks

- [x] Adjust element template with an additional method
  - [x] Consider input: channel name (FEEL or static)
  - [x] Consider input: user name (FEEL or static)
  - [x] Consider result: _probably status / success or not?_
- [x] Adjust backend implementation (connector function)
  - [x] Business logic
  - [x] Automated tests (API mock)
- [x] Adjust [documentation](https://github.com/camunda/camunda-platform-docs/)
- [x] Consider migration case
  - [x] Ensure it works by trying out: e.g., have existing process with old template applied, and then change template under the hood => see what happens
    - [x] Learning excercise: learn about the `version` attribute in element templates which can be an alternative to an implicit migration.
      - [x] Learn about it in the [docs](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/defining-templates/)
- [x] Change element template in Web Modeler
- [x] For the PR, consider existing (open?) [PR](https://github.com/camunda/web-modeler/pull/3024) by @chillleader 
    - [x] Align with @chillleader to ensure smooth delivery of this change
- [x] Deploy the new Connector run-time

__Describe alternatives you've considered__

* Create a seperate connector

__Additional context__

Part of camunda/team-connectors#238

**Comment by igpetrov** [comment]
Connector's in prod
