### ISSUE TITLE
Incorrect toString implementation for common result

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors-bundle#561]
__Describe the Bug__

__Steps to Reproduce__

1. do this
2. do that

__Expected Behavior__

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda version: [e.g. 8.0.4 (self-managed)]

**Comment by chillleader** [comment]
This has been fixed with https://github.com/camunda/connectors-bundle/pull/562
