### ISSUE TITLE
Use a spring-context-aware OutboundConnectorFactory

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/connectors-bundle#581]
__Is your feature request related to a problem? Please describe.__

When creating a connector, currently, it is not possible to use the spring context. The reason is that the DefaultConnectorFactory does not support the Spring Context

__Describe the solution you'd like__

A SpringConnectorFactory that is able to use connector instances from the spring context.

__Describe alternatives you've considered__

Instead of providing the connector class in the configuration, you could provide an instance here. This could lead to a changed lifecycle.

__Additional context__

**Comment by chillleader** [comment]
Thanks for the submission @jonathanlukas. We are actively discussing Spring support within the team right now. We want to allow developers to utilize Spring for dependency injection into connectors, however, we are concerned about delegating the lifecycle management to Spring. As a middle ground, we may support custom connector factory beans in the runtime.

We'll provide an update when we have more info on this. cc @sbuettner

**Comment by sbuettner** [comment]
* #809
