### ISSUE TITLE
Track QA status : Inbound connectors 

### ISSUE THREAD

**Issue by GeethaParthasarathy** [camunda/connectors-bundle#644]
__What should we do?__

This issue is created to track the status of **QA for Inbound connectors : SQS, Kafka, RabbitMQ** . Since multiple Connectors needs to tested and multiple stakeholders are involved in the testing process , this issue acts as a source of truth to track the status of testing.

**QA Task Breakdown:**

A checklist containing all necessary actions has been listed below and the following also indicates the order in which the QA process would take place:

- [x] Decide on a timelines for QA along with @mschoe  and inform @sbuettner on the same
       - QA will be performed between 7th and 8th of June 2023.
- [x] Create a dedicated slack channel with all necessary participants _#[prj-qa-inbound-connectors](https://join.slack.com/share/enQtNTM4MDc5OTI0MTIxOC03NzYxZDcxNTNkOWEwOTI5MGVlNWMwNjRjYmYwOTAzM2ViYTU0MjJhMjlkNzRhZTM5OTg5MTRlOWI2ZmEwYTk3)
- [x] Inform in the slack channel the order of connectors chosen to test
- [x] Archive the slack channel once QA is complete
- [ ] Delete clusters created for QA once QA is complete

 **SQS Inbound connector** 
 

- [x] Intimate the DRI- @Oleksiivanov  to create a QA Handover issue with the filled in handover checklist that includes all test setup details - _#Timeline - 7th June
- [x] Set up a sync call+ demo session with the DRI 
- [x] Create test cases in Testrail and share the link for review to the DRI in the QA Handover issue
- [x] Announce the start of  testing in the slack channel
- [x] Announce the progress of testing and issues discovered(if any) in the slack channel and the QA Handover issue
- [x] Announce completion of testing in the slack channel and write Issue summary in the QA Handover issue.
- [x] Retest any bug fixes and close the QA Handover issue once the whole QA is complete

 **RabbitMQ Inbound connector** 
     

- [x]  Intimate the DRI @chillleader to create a QA Handover issue with the filled in handover checklist that includes all test setup details - _#Timeline -7th June
- [x] Set up a sync call+ demo session with the DRI 
- [ ] Create test cases in Testrail and share the link for review to the DRI in the QA Handover issue
- [x]  Announce the start of  testing in the slack channel
- [x]  Announce the progress of testing and issues discovered(if any) in the slack channel and the QA Handover issue
- [x]  Announce completion of testing in the slack channel and write Issue summary in the QA Handover issue.
- [x]  Retest any bug fixes and close the QA Handover issue once the whole QA is complete

 **Kafka Inbound connector** 

- [x] Intimate the DRI- @igpetrov  to create a QA Handover issue with the filled in handover checklist that includes all test setup details _- #Timeline -7th June_
- [x] Set up a sync call+ demo session with the DRI 
- [ ]  Create test cases in Testrail and share the link for review to the DRI in the QA Handover issue
- [x] Announce the start of  testing in the slack channel
- [x]  Announce the progress of testing and issues discovered(if any) in the slack channel and the QA Handover issue
- [x] Announce completion of testing in the slack channel and write Issue summary in the QA Handover issue.
- [x] Retest any bug fixes and close the QA Handover issue once the whole QA is complete

**Comment by sbuettner** [comment]
@gbetances089 @GeethaParthasarathy @mschoe Please let us know if you experience minor issues like documentation usability or lack of details that can be improved in the future. Just add them as comments if they are no severe bugs. Thank you!

**Comment by sbuettner** [comment]
@GeethaParthasarathy Thanks for all your efforts. Can we close this one?

**Comment by GeethaParthasarathy** [comment]
Closing the issue as QA is complete
