### ISSUE TITLE
[Kafka inbound] topic value is missing on the response.

### ISSUE THREAD

**Issue by gbetances089** [camunda/connectors-bundle#708]
__Describe the Bug__

According to the [docs](https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/kafka-inbound/#kafka-consumer-connector-response) the value for the topic name should be returned on the response, however is not been returned.

__Steps to Reproduce__

0. Set up a Kafka instance.
1. Create a BPMN with a inbound Kafka connector.
2. Send a msg from the kafka instance.

Example: [here](https://lpp-1.operate.dev.ultrawombat.com/b27b5876-952b-40c3-a98c-4a4895b4e671/processes/2251799813755024)

`{"key":"18","rawValue":"{\"ordertime\":1497014222380,\"orderid\":18,\"itemId\":\"a4f6j2\",\"address\":{\"city\":\"Mountain View\",\"state\":\"CA\",\"zipcode\":94041}}","value":{"ordertime":1.49701422238E12,"orderid":18.0,"itemId":"a4f6j2","address":{"city":"Mountain View","state":"CA","zipcode":94041.0}}}`

__Expected Behavior__

The value of the topic is returned also on the response.

__Environment__

- OS: MacOS
- Camunda version: Zeebe 8.2

**Comment by igpetrov** [comment]
As discussed, removing from docs.

**Comment by markfarkas-camunda** [comment]
We decided not to include the topic in the response, so we removed it from the docs. See: https://github.com/camunda/camunda-platform-docs/issues/2215
