### ISSUE TITLE
Camunda operate connector for self managed not working with secrets

### ISSUE THREAD

**Issue by bulivlad** [camunda/connectors-bundle#808]
Camunda operate connector for self managed cluster is not working when using the camunda operate url as secret.

__Steps to Reproduce__

1. add camunda operate connector
2. configure it for self-managed instance
3. use secrets for `Operate base URL`
4. Run the workflow, the url is malformed

__Expected Behavior__

The camunda operate base url should be composed after the secret was replaced from the context, otherwise the search secret will be the entire operate url

__Environment__

- OS: macOS
- Library version: 0.17.1
- Camunda version: 8.1.6

**Comment by sbuettner** [comment]
Please use parentheses when using secrets for protocol connector inputs like this:
```
operate_base_url = {{secrets.MY_SECRET_OPERATE_BASE_URL}}
``` 
and

```
oauthTokenEndpoint = {{secrets.MY_SECRET_OAUTH_TOKEN_ENDPOINT}} 
```

Please let us know if you are facing any issues with that approach or whether it works for you.

**Comment by bulivlad** [comment]
using `{{secrets.MY_SECRET}}` might work but the http-json connector is using a different validation pattern `@Pattern(regexp = "^(http://|https://|secrets).*$")` which does not allow `{{}}`. so basically the secrets replacement will work but the url field validation will fail

**Comment by sbuettner** [comment]
@bulivlad Thanks for your reply. 

Which version of the connector runtime are you using? 

The latest connector version accepts the following pattern:

https://github.com/camunda/connectors-bundle/blob/1354faa3d99a08312d3c9a98df9f11361d14a2f0/connectors/connectors-common-library/src/main/java/io/camunda/connector/common/model/CommonRequest.java#L29

**Comment by bulivlad** [comment]
@sbuettner thanks for highlighting it. You are right, I'm on v0.17.1. You can probably close this one as it was fixed in latest version. However it would be nice to see some consistency across secrets notation between `secrets.MY_SECRET` and `{{ secrets.MY_SECRET }}`

Cheers

**Comment by sbuettner** [comment]
@bulivlad Thanks for getting back. Yes, we will improve the documentation in this regarding. Have a great week!
