### ISSUE TITLE
Inbound Kafka Connectors limited by CPU Count

### ISSUE THREAD

**Issue by eslateBP3** [camunda/connectors-bundle#845]
__Describe the Bug__

I am using Kafka connectors in a BPMN diagram. I have both inbound and outbound connectors.
Running Camunda Self Managed 8.2.4 via docker-compose files. There are 5 CPUs allocated to Docker.
With 4 or fewer inbound connectors, everything works as expected.
If I exceed 4 inbound connectors, only 4 will successfully subscribe / activate. If I have 5, for example, all 5 will send subscription activation requests but only 4 will succeed. If I then remove one of the ones that previously activated and re-deploy, the next one will successfully subscribe / activate.

This seems to be related to the number of threads available in the thread pool (thread pool being used by Kafka Connector implementation is set to CPUs - 1) and how many are used by each Kafka consumer.

- Each Kafka consumer creates a thread.
- Camunda connectors use CompletableFuture which uses ForkJoinPool.commonPool, which is a CPU bound thread pool. The default settings for maximum number of threads is number of runtime processors - 1.
- See startConsumer() method [here](https://github.com/camunda/connectors-bundle/blob/main/connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java).
- I just checked my local Docker Desktop settings and CPUs were set to 5 (so limiting me to 4 consumers makes sense). Changed the setting to 6 and restarted and 5 consumers successfully subscribed.
- Adding a 6th consumer results in the first 5 successfully subscribing and the 6th is unable to subscribe.

__Steps to Reproduce__

1. Build a BPMN diagram with a Start event that is a Kafka consumer connector.
2. Add a parallel gateway that flows to 4 stand-alone Kafka consumer connector events.
3. Create a Kafka topic or topic(s) that correspond with the Kafka connector configuration values.
4. Start a self-managed Camunda cluster. Ensure the machine has 3 - 5 CPUs allocated.
5. Watch the Connector logs as you deploy your diagram.
6. Log entries for subscription activation request should appear for all configured inbound connectors upon deployment:
`INFO 1 --- [   scheduling-1] i.c.c.kafka.inbound.KafkaExecutable      : Subscription activation requested by the Connector runtime: KafkaConnectorProperties{authenticationType='credentials', authentication=null, topic=KafkaTopic{bootstrapServers='secrets.KAFKA_SERVER', topicName='bpmn-start-events'}, additionalProperties={group.id=tlb-start}, activationCondition='=key = "TLB_START_SANDBOX"', offsets=null, autoOffsetReset='latest'}`

For the connectors that successfully subscribe, I see a ConsumerConfig output:
`
INFO 1 --- [onPool-worker-3] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
2023-07-06 15:36:01     allow.auto.create.topics = true
2023-07-06 15:36:01     auto.commit.interval.ms = 5000
2023-07-06 15:36:01     auto.include.jmx.reporter = true
2023-07-06 15:36:01     auto.offset.reset = latest
` [...]

and
`INFO 1 --- [onPool-worker-3] o.a.k.clients.consumer.KafkaConsumer     : [Consumer clientId=consumer-tlb-start-16, groupId=tlb-start] Assigned to partition(s): bpmn-start-events-0`

and
`INFO 1 --- [onPool-worker-3] i.c.c.k.inbound.KafkaConnectorConsumer   : Kafka inbound connector initialized`

For the connectors that fail to subscribe, I only see the subscription activation request but no further info on the Kafka nor Camunda side.

__Expected Behavior__

All correctly configured inbound Kafka connectors that make a subscription activation request are successfully subscribed (within reasonable limits).

__Environment__

- OS: Mac OS X Ventura 13.4.1 (22F82)
- Library version: Connectors 0.20.2
- Camunda version: 8.2.4 (self-managed)

__Workaround__

- Add `-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` to startup parameters and any number of consumers will work.
- The `number of CPUs - 1` sets the JVM's parallelism value but we can directly set the value to not have the threads restricted by CPU count.
- In the common pool, there are three modes you can achieve ([source](https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool)):
-- parallelism > 2 — JDK creates the (# of CPUs - 1) threads for the commonPool
-- parallelism = 1 — JDK creates a new thread for every submitted task
-- parallelism = 0 — a submitted task is executed on a caller thread

**Comment by eslateBP3** [comment]
This seems to be related to the number of threads available in the thread pool and how many are used by each Kafka consumer.

- Each Kafka consumer creates a thread.
- Camunda connectors use CompletableFuture which uses ForkJoinPool.commonPool, which is a CPU bound thread pool. The default settings for maximum number of threads is number of runtime processors - 1.
- I just checked my local Docker Desktop settings and CPUs were set to 5 (so limiting me to 4 consumers makes sense). Changed the setting to 6 and restarted and 5 consumers successfully subscribed.
- Adding a 6th consumer results in the first 5 successfully subscribing and the 6th is unable to subscribe.

**Comment by sbuettner** [comment]
@markfarkas-camunda I would recommend to take a look at this blog post: https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool which is used by the implementation.

**Comment by markfarkas-camunda** [comment]
This [PR](https://github.com/camunda/connectors-bundle/pull/895) solves the issue.

**Comment by eslateBP3** [comment]
Thank you! Have confirmed this is working for me now. 15 consumers all validated successfully in a JVM with 10 available CPUs.
